imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: easyadmin/ }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.path.badge_images: /uploads/images/badges

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    translator: { fallback: en }

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    date:
        timezone: America/Chicago
    globals:
        fos_csrf_provider: "@security.csrf.token_manager"

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                group_concat: DoctrineExtensions\Query\Mysql\GroupConcat
            datetime_functions:
                year: DoctrineExtensions\Query\Mysql\Year

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    encryption: '%mailer_encryption%'
    auth_mode: '%mailer_auth_mode%'
    host: '%mailer_host%'
    port: '%mailer_port%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool:     { type: memory }

# FOSUserBundle
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_from%"
        sender_name: "%mailer_fromName%"

white_october_tcpdf:
    class: 'AppBundle\Service\TCPDF\RegistrationPDF'
    tcpdf:
        k_tcpdf_external_config: true
        k_path_fonts: '../app/Resources/fonts/'
        pdf_page_format: 'LETTER'
        pdf_unit: 'pt'

vich_uploader:
    db_driver: orm
    mappings:
        badge_images:
            uri_prefix:         '%app.path.badge_images%'
            upload_destination: '%kernel.root_dir%/images/badges'
            namer:              Vich\UploaderBundle\Naming\UniqidNamer

easy_admin:
    design:
        brand_color: '#fe7f00'
        color_scheme: 'light'
        menu:
            - { route: 'homepage', label: 'Return to Homepage', icon: 'arrow-left' }
            - label: 'IT'
              icon: 'laptop'
              children:
                - { entity: 'Event', icon: 'calendar' }
                - { entity: 'User', icon: 'user-circle' }
                - { entity: 'EventBadgeType', icon: 'id-badge' }
    site_name: 'Anime Detour'

    list:
        actions: [{ name: 'edit', icon: 'pencil' }, '-delete']