# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_MERCH:       ROLE_USER
        ROLE_VOLUNTEERS:  ROLE_USER
        ROLE_STATISTICS:  ROLE_USER
        ROLE_EXEC:        [ROLE_USER, ROLE_STATISTICS]
        ROLE_REGSTAFF:    [ROLE_USER, ROLE_MERCH, ROLE_VOLUNTEERS, ROLE_STATISTICS]
        ROLE_SUBHEAD:     ROLE_REGSTAFF
        ROLE_ADMIN:       ROLE_SUBHEAD
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: /login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true


    access_control:
        - { path: ^/register, role: ROLE_SUPER_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }