# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    entity_event:
        class: AppBundle\Service\Entity\Event
        arguments: [ "@doctrine.orm.entity_manager"]

    entity_badgetype:
        class: AppBundle\Service\Entity\BadgeType
        arguments: [ "@doctrine.orm.entity_manager"]

    util_percent:
        class: AppBundle\Service\Util\Percent
        arguments: [ "@entity_event", "@entity_badgetype", "@doctrine.orm.entity_manager"]