# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    my.set_created:
        arguments: ['@service_container']
        class: AppBundle\EventListener\CreatedModifiedFields
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    my.set_updated:
        arguments: ['@service_container']
        class: AppBundle\EventListener\CreatedModifiedFields
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    util_email:
        class: AppBundle\Service\Util\Email
        arguments: [ "@templating", '@mailer', "@doctrine.orm.entity_manager"]

    util_percent:
        class: AppBundle\Service\Util\Percent
        arguments: [ "@doctrine.orm.entity_manager"]

    repository_tcpdf:
        class: AppBundle\Service\TCPDF\PDFRepository
        arguments: [ "@doctrine.orm.entity_manager"]

