# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    repository_event:
        class: AppBundle\Service\Entity\EventRepository
        arguments: [ "@doctrine.orm.entity_manager"]

    repository_badgetype:
        class: AppBundle\Service\Entity\BadgeTypeRepository
        arguments: [ "@doctrine.orm.entity_manager"]

    repository_registration:
        class: AppBundle\Service\Entity\RegistrationRepository
        arguments: [ "@repository_event", "@doctrine.orm.entity_manager"]

    util_percent:
        class: AppBundle\Service\Util\Percent
        arguments: [ "@repository_event", "@repository_badgetype", "@doctrine.orm.entity_manager"]