# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    repository_badge:
        class: AppBundle\Service\Repository\BadgeRepository
        arguments: [ "@doctrine.orm.entity_manager"]

    repository_event:
        class: AppBundle\Service\Repository\EventRepository
        arguments: [ "@doctrine.orm.entity_manager"]

    repository_badgetype:
        class: AppBundle\Service\Repository\BadgeTypeRepository
        arguments: [ "@doctrine.orm.entity_manager"]

    repository_registration:
        class: AppBundle\Service\Repository\RegistrationRepository
        arguments: [ "@repository_event", "@doctrine.orm.entity_manager"]

    repository_registrationshirt:
        class: AppBundle\Service\Repository\RegistrationShirtRepository
        arguments: [ "@doctrine.orm.entity_manager"]

    repository_registrationstatus:
        class: AppBundle\Service\Repository\RegistrationStatusRepository
        arguments: [ "@doctrine.orm.entity_manager"]

    repository_registrationtype:
        class: AppBundle\Service\Repository\RegistrationTypeRepository
        arguments: [ "@doctrine.orm.entity_manager"]

    repository_registrationhistory:
        class: AppBundle\Service\Repository\RegistrationHistoryRepository
        arguments: [ "@doctrine.orm.entity_manager"]

    repository_reggroup:
        class: AppBundle\Service\Repository\RegGroupRepository
        arguments: [ "@doctrine.orm.entity_manager"]

    repository_shirt:
        class: AppBundle\Service\Repository\ShirtRepository
        arguments: [ "@doctrine.orm.entity_manager"]

    util_percent:
        class: AppBundle\Service\Util\Percent
        arguments: [ "@repository_event", "@repository_badgetype", "@doctrine.orm.entity_manager"]