easy_admin:
    entities:
        Department:
            class: AppBundle\Entity\Organization\Department
            disabled_actions: ['delete']
            label: 'Departments'
            list:
                fields:
                    - { property: 'name' }
                    - { property: 'description' }
                    - { property: 'externalEmail' }
                    - { property: 'active', type: 'boolean' }
            form:
                fields:
                    - { property: 'name' }
                    - { property: 'description' }
                    - { property: 'externalEmail' }
                    - { property: 'allStaffReceiveExternalEmail' }
                    - { property: 'internalEmail' }
                    - { property: 'active' }