easy_admin:
    entities:
        Event:
            class: AppBundle\Entity\Event
            disabled_actions: ['delete']
            label: 'List of Years'
            list:
                fields:
                    - { property: 'year' }
                    - { property: 'startDate', format: 'M jS Y', type_options: { required: true } }
                    - { property: 'endDate', format: 'M jS Y', type_options: { required: true } }
                    - { property: 'attendanceCap' }
            form:
                actions:
                    - { name: 'makeActive', icon: 'plus-square' }
                fields:
                    - { property: 'year' }
                    - {
                        property: 'startDate',
                        format: 'n/j/Y',
                        type: 'date'
                      }
                    - {
                        property: 'endDate',
                        format: 'n/j/Y',
                        type: 'date'
                      }
                    - { property: 'attendanceCap' }