easy_admin:
    entities:
        User:
            disabled_actions: ['delete']
            label: 'Users list'
            class: AppBundle\Entity\User
            search:
                sort: ['lastName', 'ASC']
            list:
                sort: ['lastName', 'ASC']
                dql_filter: 'entity.enabled = true'
                fields:
                    - lastname
                    - firstName
                    - { property: 'roles' }
                    - email
                    - { property: 'enabled', type: 'boolean' }

            show:
                fields:
                    - username
                    - lastname
                    - firstname
                    - email
                    - enabled
                    - lastLogin
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'Basic User': 'ROLE_USER', 'Merchandise': 'ROLE_MERCH', 'Volunteers': 'ROLE_VOLUNTEERS', 'Registration Subhead': 'ROLE_SUBHEAD', 'Admin': 'ROLE_ADMIN' } } }
                    - createdBy
                    - createdDate
                    - modifiedBy
                    - modifiedDate
                form_options: { validation_groups: ['Profile'] }

            edit:
                title: 'Edit User'
                actions: ['show', '-delete']
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Basic information' }
                    - { property: 'lastName', type_options: { required: true } }
                    - { property: 'firstName', type_options: { required: true } }
                    - { property: 'email', type: 'email', type_options: { required: true } }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Login information' }
                    - { property: 'username', type_options: { required: true } }
                    #- { property: 'password', type_options: { required: true } }
                    - { property: 'plainPassword', label: 'Password', type: 'password', type_options: { required: false } }
                    - { type: 'group', css_class: 'col-sm-12', label: 'Permissions' }
                    - { property: 'enabled' }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'Basic User': 'ROLE_USER', 'Merchandise': 'ROLE_MERCH', 'Volunteers': 'ROLE_VOLUNTEERS', 'Registration Subhead': 'ROLE_SUBHEAD', 'Admin': 'ROLE_ADMIN' } } }
                form_options: { validation_groups: ['Profile'] }
            new:
                title: 'Add new User'
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Basic information' }
                    - { property: 'lastName', type_options: { required: true } }
                    - { property: 'firstName', type_options: { required: true } }
                    - { property: 'email', type: 'email', type_options: { required: true } }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Login information' }
                    - { property: 'username', type_options: { required: true } }
                    #- { property: 'password', type_options: { required: true } }
                    - { property: 'plainPassword', label: 'Password', type: 'password', type_options: { required: false } }
                    - { type: 'group', css_class: 'col-sm-12', label: 'Permissions' }
                    - { property: 'enabled', type_options: { required: true } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'Basic User': 'ROLE_USER', 'Merchandise': 'ROLE_MERCH', 'Volunteers': 'ROLE_VOLUNTEERS', 'Registration Subhead': 'ROLE_SUBHEAD', 'Admin': 'ROLE_ADMIN' } } }
                form_options: { validation_groups: ['Registration'] }